### ISSUE TITLE
`cargo install semantic-release-rust` not found

### ISSUE THREAD

**Issue by shunkakinoki** [sbosnick/semantic-release-rust#20]
Thanks for the awesome library!
Found that the command specified in the README did not work.

Output:
```
error: could not find `semantic-release-rust` in registry `https://github.com/rust-lang/crates.io-index` with version `*`
```

**Comment by sbosnick** [comment]
Thank you for reporting this. I will change the `cargo install` command listed in the README.md file.

This is a temporary problem that appears to be cause by the fact that the only published versions of the crate are pre-release version. Once I publish the 1.0.0 version that the `cargo install` command currently listed in README.md should work.

If you have time it would assist me if you could try the following command to see if it works on your machine:

```shell
cargo install semantic-release-rust --version 1.0.0-alpha.6
```

This works on my machine and on the one project that I use `semantic-release-rust` on but it would be helpful to test is on someone else's machine as well. If this works then that is what I will change README.md to.

**Comment by shunkakinoki** [comment]
Thanks for the followup!
```
cargo install semantic-release-rust --version 1.0.0-alpha.6
```
The above command worked, really appreciate your work!
